VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
  Persistable = 0  'NotPersistable
  DataBindingBehavior = 0  'vbNone
  DataSourceBehavior  = 0  'vbNone
  MTSTransactionMode  = 0  'NotAnMTSObject
END
Attribute VB_Name = "ReparationBase"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = True
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Attribute VB_Ext_KEY = "SavedWithClassBuilder6" ,"Yes"
Attribute VB_Ext_KEY = "Top_Level" ,"Yes"
'local variable(s) to hold property value(s)
Private mvarRepNo As Double 'local copy
Public Property Let RepNo(ByVal vData As Double)
'used when assigning a value to the property, on the left side of an assignment.
'Syntax: X.RepNo = 5
    mvarRepNo = vData
End Property


Public Property Get RepNo() As Double
'used when retrieving value of a property, on the right side of an assignment.
'Syntax: Debug.Print X.RepNo
    RepNo = mvarRepNo
End Property



